
# docker- prefix due to files in docker/ folder
FROM ghcr.io/usa-reddragon/indi.base:main

COPY --chown=allsky:allsky docker/start_indiserver.sh /home/allsky
RUN chmod 755 /home/allsky/start_indiserver.sh

ENTRYPOINT ["./start_indiserver.sh"]
