FROM ghcr.io/usa-reddragon/indi-base:v2.1.0@sha256:f0bb745c29677e58780e7051c2a524439a1db6d054b41a945cf42c3ea36f0722

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get -y install \
      --no-install-recommends \
      --no-install-suggests \
      iputils-ping \
      iproute2 \
      bind9-host \
      locales \
      tzdata \
      procps \
      netcat-traditional \
      sudo \
      git \
      jq \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN groupadd --gid 10001 allsky \
    && useradd --create-home --no-user-group --uid 10001 --gid allsky --groups dialout,video --home-dir /home/allsky --shell /bin/bash allsky

RUN echo "allsky ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/allsky \
    && chmod 0440 /etc/sudoers.d/allsky

USER allsky
