FROM ghcr.io/usa-reddragon/indi.base:main AS indi.allsky.base

USER root

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get -y install \
      --no-install-recommends \
      --no-install-suggests \
        python3 \
        python3-venv \
        python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -m 750 /etc/indi-allsky
RUN chown -R allsky:allsky /etc/indi-allsky

RUN mkdir -p -m 755 /var/www/html/allsky
RUN chown -R allsky:allsky /var/www/html/allsky
VOLUME /var/www/html/indi-allsky

USER allsky
WORKDIR /home/allsky

RUN mkdir -m 755 /var/www/html/allsky/images
RUN mkdir -m 755 /var/www/html/allsky/images/darks
RUN mkdir -m 755 /var/www/html/allsky/images/export

COPY requirements/requirements_latest.txt /home/allsky
COPY requirements/requirements_optional.txt /home/allsky
COPY requirements/requirements_gpio.txt /home/allsky

RUN python3 -m venv /home/allsky/venv
ENV VIRTUAL_ENV=/home/allsky/venv

RUN /home/allsky/venv/bin/pip3 install --no-cache-dir --upgrade pip setuptools wheel

USER root
RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get -y install \
      --no-install-recommends \
      --no-install-suggests \
        clang \
        cmake \
        build-essential \
        pkg-config \
        libdbus-1-dev \
        libdbus-1-3 \
        libglib2.0-dev\
        libglib2.0-0 \
        libcfitsio-dev \
        libnova-dev \
        python3-dev \
        dbus-daemon \
        swig \
    && export CC=clang \
    && export CXX=clang++ \
    && /home/allsky/venv/bin/pip3 install --no-cache-dir -r requirements_latest.txt -r requirements_optional.txt -r requirements_gpio.txt \
    && /home/allsky/venv/bin/pip3 install --no-cache-dir "git+https://github.com/indilib/pyindi-client.git@674706f#egg=pyindi-client" \
    && apt-get remove --purge -y \
        clang \
        cmake \
        build-essential \
        pkg-config \
        libdbus-1-dev \
        libglib2.0-dev \
        libcfitsio-dev \
        libnova-dev \
        python3-dev \
        dbus-daemon \
        swig \
    && apt-get autoremove --purge -y \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && chown -R allsky:allsky /home/allsky

USER allsky
